"""What a failed criterion tells you: a broken scene, or a badly configured solver.

An acceptance report that only says which criteria failed cannot be acted on. Retuning the
solver after a genuine scene defect hides the defect; declaring a scene bad after a solver
misconfiguration blames the scene for an artefact. The two are distinguishable, and the
distinction is measured rather than asserted:

Sweeping contact stiffness over its whole legal range on one unchanged resting scene
(constraint_timeconst 0.008 -> 0.05 at dt=0.004) moved the criteria by very different
amounts. Steady penetration went 0.034 mm -> 0.697 mm, a factor of 20, purely from the
solver knob. Over the same sweep drift_rate moved 8.3e-7 -> 1.3e-6 m/s, a factor of 1.6,
and stayed three orders of magnitude inside its limit throughout. A criterion that swings
twentyfold on a setting the scene never saw is reporting the solver; one that barely moves
is reporting the scene.
"""

from __future__ import annotations

# A failure here means the body really did move, slide, tip, or lose its declared support.
# Retuning numerics in response is how a real defect gets tuned away, so callers must stop.
SCENE_TRUTH = "scene_truth"
# A failure here may be the discretisation rather than the scene, so a different numerical
# configuration is a legitimate next step -- within a bounded, recorded search.
NUMERICS_COUPLED = "numerics_coupled"
# Reported for context; never decides pass or fail on its own.
DIAGNOSTIC = "diagnostic"

CATEGORIES = {
    # -- single-asset and scene entrances: pose evolution is the primary rest criterion --
    "translation_m": SCENE_TRUTH,
    "rotation_deg": SCENE_TRUTH,
    "drift_rate_mps": SCENE_TRUTH,
    "excursion_m": SCENE_TRUTH,
    "rotation_rate_dps": SCENE_TRUTH,
    # The limit is derived from g*dt, but longest_run() already rejects the isolated spikes
    # a dropout produces. Tripping it needs sustained motion, which no solver setting
    # invents, so a failure is the body and not the step size.
    "speed_run_steps": SCENE_TRUTH,
    "support_fraction": SCENE_TRUTH,
    # -- the two the solver owns --
    # Contact force is generated by letting the bodies overlap, so depth is set by contact
    # stiffness, not by whether the scene is correct.
    "penetration_m": NUMERICS_COUPLED,
    # The dropout limit cycle is a contact-detection artefact of a stiff solve.
    "contact_dropout_max": NUMERICS_COUPLED,
    "effective_speed_max_mps": DIAGNOSTIC,
    # -- repair_physics names the same ideas differently --
    "pose_drift": SCENE_TRUTH,
    "pose_rotation": SCENE_TRUTH,
    "stable_velocity": SCENE_TRUTH,
    "support_preserved": SCENE_TRUTH,
    "support_geometry": SCENE_TRUTH,
    "unsupported_support_tilt": SCENE_TRUTH,
    "tipped": SCENE_TRUTH,
    "scene_bounds": SCENE_TRUTH,
    "below_ground": SCENE_TRUTH,
    "unexpected_contact": SCENE_TRUTH,
    "text_relation": SCENE_TRUTH,
    "penetration": NUMERICS_COUPLED,
    "contact_continuity": NUMERICS_COUPLED,
}

# Above this share of the penetration budget spent while merely resting, the solve is
# reporting its own compliance rather than the scene's geometry: at constraint_timeconst
# 0.05 a 60 g body at rest already sits 0.697 mm into a 1 mm budget, leaving no room for
# any approach transient. Diagnostic only -- it never turns a pass into a failure.
SATURATED_BUDGET = 0.5


def category(name):
    """Category of one criterion; unknown names are a coverage bug, not a default."""
    if name not in CATEGORIES:
        raise KeyError(f"uncategorised physics criterion: {name}")
    return CATEGORIES[name]


def classify(failed):
    """Split failed criterion names by what they implicate."""
    names = list(failed)
    return dict(
        scene_truth=[n for n in names if category(n) == SCENE_TRUTH],
        numerics_coupled=[n for n in names if category(n) == NUMERICS_COUPLED],
    )


def tunable(failed):
    """True when every failure is one a different numerical configuration could fix.

    False both when a scene-truth criterion failed -- the scene is wrong and retuning would
    only hide it -- and when nothing failed at all, since there is then nothing to tune.
    """
    split = classify(failed)
    return not split["scene_truth"] and bool(split["numerics_coupled"])


def budget_used(window_penetration_m, limit_m):
    """Share of the penetration budget the solver spends just holding the body up."""
    if not limit_m or limit_m <= 0:
        raise ValueError("penetration limit must be positive")
    return float(window_penetration_m) / float(limit_m)


def annotate(checks, *, window_penetration_m=None, penetration_limit_m=None):
    """Attach a category to every check, plus the resting penetration budget when known."""
    annotated = [dict(c, category=category(c["name"])) for c in checks]
    if window_penetration_m is None or penetration_limit_m is None:
        return annotated, {}
    used = budget_used(window_penetration_m, penetration_limit_m)
    return annotated, dict(
        penetration_budget_used=used,
        # Names the situation the sweep above describes, so a caller reading the report can
        # tell "the scene barely clears the limit" from "the solver already spent it".
        numerics_saturated=used > SATURATED_BUDGET,
    )
